// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-g4cEHeBFfrkxivbtU3BX0EPqqFj7U0',
    appId: '1:999437205944:web:9d95a545641e2020130f4d',
    messagingSenderId: '999437205944',
    projectId: 'modulo04-71536',
    authDomain: 'modulo04-71536.firebaseapp.com',
    databaseURL: 'https://modulo04-71536-default-rtdb.firebaseio.com',
    storageBucket: 'modulo04-71536.appspot.com',
    measurementId: 'G-R8PBR35ENS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4NugDt3TbEw6osZvLHWS8CdFXKdup2WA',
    appId: '1:999437205944:android:c88eba533bf8d4ef130f4d',
    messagingSenderId: '999437205944',
    projectId: 'modulo04-71536',
    databaseURL: 'https://modulo04-71536-default-rtdb.firebaseio.com',
    storageBucket: 'modulo04-71536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIN18r3iBqMjYIoUCI4us_zBIpOieq638',
    appId: '1:999437205944:ios:63d59fab3c440623130f4d',
    messagingSenderId: '999437205944',
    projectId: 'modulo04-71536',
    databaseURL: 'https://modulo04-71536-default-rtdb.firebaseio.com',
    storageBucket: 'modulo04-71536.appspot.com',
    iosBundleId: 'com.example.modulo04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIN18r3iBqMjYIoUCI4us_zBIpOieq638',
    appId: '1:999437205944:ios:790d1ec428118a3e130f4d',
    messagingSenderId: '999437205944',
    projectId: 'modulo04-71536',
    databaseURL: 'https://modulo04-71536-default-rtdb.firebaseio.com',
    storageBucket: 'modulo04-71536.appspot.com',
    iosBundleId: 'com.example.modulo04.RunnerTests',
  );
}
