// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBigEpf0vd-uPP9OyxK4IkHUCJ9d1Ja-yI',
    appId: '1:2963142092:web:681592baf80a6586745969',
    messagingSenderId: '2963142092',
    projectId: 'modulo07',
    authDomain: 'modulo07.firebaseapp.com',
    databaseURL: 'https://modulo07-default-rtdb.firebaseio.com',
    storageBucket: 'modulo07.appspot.com',
    measurementId: 'G-SP4SNT5LWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOr8pf6U0IfMdMr6nSPMij9T3f_sXnBmg',
    appId: '1:2963142092:android:552d9c3196f8a8bb745969',
    messagingSenderId: '2963142092',
    projectId: 'modulo07',
    databaseURL: 'https://modulo07-default-rtdb.firebaseio.com',
    storageBucket: 'modulo07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLPobNrqCzKzZpdo_dhO7DyLieBSA2d0',
    appId: '1:2963142092:ios:f6336e157cea66c4745969',
    messagingSenderId: '2963142092',
    projectId: 'modulo07',
    databaseURL: 'https://modulo07-default-rtdb.firebaseio.com',
    storageBucket: 'modulo07.appspot.com',
    iosBundleId: 'com.example.modulo10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLPobNrqCzKzZpdo_dhO7DyLieBSA2d0',
    appId: '1:2963142092:ios:bd760a096b4bcb7c745969',
    messagingSenderId: '2963142092',
    projectId: 'modulo07',
    databaseURL: 'https://modulo07-default-rtdb.firebaseio.com',
    storageBucket: 'modulo07.appspot.com',
    iosBundleId: 'com.example.modulo10.RunnerTests',
  );
}
