// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGYecClVc9l9L8-OF37TAnqgaqqbRWEWk',
    appId: '1:1097388093254:web:f49b1dd46573023cecbf47',
    messagingSenderId: '1097388093254',
    projectId: 'treinamento-spskills',
    authDomain: 'treinamento-spskills.firebaseapp.com',
    databaseURL: 'https://treinamento-spskills-default-rtdb.firebaseio.com',
    storageBucket: 'treinamento-spskills.appspot.com',
    measurementId: 'G-73JWPQ1MX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY5p0mhs6x38jgpo7xseRmk03NrRQPHj4',
    appId: '1:1097388093254:android:ca346ab55e8b0b77ecbf47',
    messagingSenderId: '1097388093254',
    projectId: 'treinamento-spskills',
    databaseURL: 'https://treinamento-spskills-default-rtdb.firebaseio.com',
    storageBucket: 'treinamento-spskills.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6uztXjN9XaYxaRWtfU9cqOC0Wzwfnn64',
    appId: '1:1097388093254:ios:6be96779930b2543ecbf47',
    messagingSenderId: '1097388093254',
    projectId: 'treinamento-spskills',
    databaseURL: 'https://treinamento-spskills-default-rtdb.firebaseio.com',
    storageBucket: 'treinamento-spskills.appspot.com',
    iosClientId: '1097388093254-700ns5guosjpa54klk0dhh6o4qhvle70.apps.googleusercontent.com',
    iosBundleId: 'com.example.modulo07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6uztXjN9XaYxaRWtfU9cqOC0Wzwfnn64',
    appId: '1:1097388093254:ios:e253517526f5bf95ecbf47',
    messagingSenderId: '1097388093254',
    projectId: 'treinamento-spskills',
    databaseURL: 'https://treinamento-spskills-default-rtdb.firebaseio.com',
    storageBucket: 'treinamento-spskills.appspot.com',
    iosClientId: '1097388093254-ntkeu6krpbn1a2c6g4njhab561mfthb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.modulo07.RunnerTests',
  );
}
